# Generated by Django 2.2.6 on 2020-08-12 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=64, verbose_name='会议类别')),
                ('theme', models.CharField(max_length=64, verbose_name='会议主题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='会议内容')),
                ('record_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='会议时间')),
                ('operator', models.CharField(max_length=64, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '会议记录',
                'verbose_name_plural': '会议记录',
            },
        ),
    ]
